version: "3.9"

services:
  db:
    build:
      context: ".docker/postgres"
      dockerfile: Dockerfile
    ports:
      - "5432:5432"
    networks:
      - spring
    environment:
      POSTGRES_USER: suvres
      POSTGRES_PASSWORD: suvres
      POSTGRES_DB: suvres

  alpine:
    build:
      context: ".docker/alpine"
      dockerfile: Dockerfile
    working_dir: /app/
    networks:
      - spring
    tty: true
#    stdin_open: true
    ports:
      - "8080:8080"


networks:
  spring: